config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  get 'rulles', to: 'home#rulles'
  resources :juries
  resources :challenges
  resources :participates

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
  end

  namespace :challenge_juries do
    get '/', to: 'dashboard#index', as: :dashboard
  end

  namespace :challenge_members do
    namespace :participations_wizard do
      resources :generals, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :members, class_name: 'User', through: :challenge_members
  has_many :challenge_members

  enum status: { finnished: 0, in_progress: 1, upcoming: 2, archived: 3 }
  enum technology: { fdm: 0, sla: 1, sls: 2 }
  enum participation: { free: 0, paid: 1 }
end

app/models/challenge_member.rb
class ChallengeMember < ApplicationRecord
  belongs_to :challenge
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :challenges, through: :challenge_members
  has_many :rankings

  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { challenge_member: 0, moderator: 1, jury: 2, admin: 3 }
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :challenge_member
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    layout 'admin'
    before_action :authorize_admin

    private

    def authorize_admin
      authorize :admin, :access?
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < BaseController
    def index
      @users_count = User.count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError do |error|
    redirect_to root_path, alert: pundit_error_message(error)
  end

  private

  def pundit_error_message(error)
    policy = error.try(:policy)
    return default_error_message if policy.nil?

    query = error.try(:query)
    return default_error_message if query.nil?

    policy_namespace = policy.class.name.underscore
    I18n.t query, scope: [:error_message, :pundit, policy_namespace], default: default_error_message
  end

  def default_error_message
    I18n.t('error_message.pundit.default')
  end
end

app/controllers/challange_juries/base_controller.rb
# frozen_string_literal: true

module ChallangeJuries
  class BaseController < ApplicationController
    layout 'jury'
    before_action :authorize_jury

    private

    def authorize_jury
      authorize :jury, :access?
    end
  end
end

app/controllers/challange_juries/dashboard_controller.rb
# frozen_string_literal: true

module ChallangeJuries
  class DashboardController < BaseController
    def index
      @users_count = User.count
    end
  end
end

app/controllers/challenge_juries/base_controller.rb
# frozen_string_literal: true

module ChallengeJuries
  class BaseController < ApplicationController
    layout 'jury'
    before_action :authorize_jury

    private

    def authorize_jury
      authorize :jury, :access?
    end
  end
end

app/controllers/challenge_juries/dashboard_controller.rb
# frozen_string_literal: true

module ChallengeJuries
  class DashboardController < BaseController
    def index
      @users_count = User.count
    end
  end
end

app/controllers/challenge_members/base_controller.rb
# frozen_string_literal: true

module ChallengeMembers
  class BaseController < ApplicationController
    # before_action :authorize_jury

    # private

    # def authorize_jury
    #   authorize :jury, :access?
    # end
  end
end

app/controllers/challenge_members/participations_wizard/generals_controller.rb
# frozen_string_literal: true

module ChallengeMembers
  module ParticipationsWizard
    class GeneralsController < BaseController
      def new
        @challenge_member = ChallengeMember.new
      end
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :find_challenges, only: [:index]
  before_action :find_data, only: [:show]
  helper_method :state

  def index; end

  def show; end

  private

  def state
    case params[:state]
    when 'finnished'
      :finnished
    when 'in_progress'
      :in_progress
    end
  end

  def find_challenges
    @challenges = Challenge.all
    case state
    when :finnished
      @challenges = @challenges.finnished
    when :in_progress
      @challenges = @challenges.in_progress
    end
  end

  def find_data
    @challenge = Challenge.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def rulles; end
end

app/controllers/juries_controller.rb
class JuriesController < ApplicationController
  def index
    @juries = User.jury
  end

  def show
    @jury = User.find(params[:id])
  end
end

app/controllers/participates_controller.rb
class ParticipatesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>

app/views/challange_juries/dashboard/index.html.erb
<h1>Jury Dashboard</h1>

app/views/home/index.html.erb
<div id="home">
  <div class="container">
    <!-- Hero section -->
    <div class="pt-[120px] pb-[220px] flex flex-col items-start gap-[34px] max-w-lg">
      <h1 class="title drop-shadow">Print Weekly Challenge</h1>
      <p class="text-xl">Welcome to our platform for the 3D printing community! We're dedicated to fostering creativity, innovation, and collaboration among 3D printing enthusiasts of all skill levels. Every Monday, we release a new prompt to inspire your designs, and we invite you to submit your creations for a chance to be featured on our website and social media channels.</p>
    </div>
    <div class="pt-[120px] pb-[220px] flex flex-col items-start gap-[34px] max-w-lg">
      <p class="text-xl">Our community is full of talented and passionate makers who are always eager to share their knowledge and expertise, so feel free to join the conversation and connect with like-minded individuals. Whether you're a seasoned pro or just starting out, we hope you'll find a home here and that our platform will help you take your 3D printing skills to the next level. So what are you waiting for? Check out these fantastic submissions to our Monday Prompts and get inspired!</p>
    </div>

    <!-- Info section -->
    <div class="flex justify-between items-center pb-3">
      <h3 class="font-semibold text-2xl leading-7">Current Challenges</h3>
      <%= link_to "See all", challenges_path(state: "in_progress"), class: "text-2xl leading-none underline" %>
    </div>
    <div class="flex items-center gap-36 pb-28">
      <%= image_tag("pexels-rodion.png", size: "640x550", alt: "img", class: "w-full max-w-[49%]") %>

      <div class="flex flex-col items-start gap-[14px]">
        <div class="py-1 px-3 bg-darkblue">
          <span class="text-creamlight font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
        </div>

        <h4 class="font-bold text-2xl leading-[30px] max-w-sm pb-[22px]">Name Of The New Challenge In Two Lines</h4>
        <p class="text-xl pb-[22px] max-w-md">Short description about it. Check out these fantastic submissions to our Monday Prompts. Here will be some text, some more.</p>

        <div class="flex gap-20">
          <div class="flex flex-col gap-[3px]">
            <h6 class="font-bold text-2xl leading-none">24</h6>
            <span class="text-base">Candidates</span>
          </div>

          <div class="flex flex-col gap-[3px]">
            <h6 class="font-bold text-2xl leading-none">$200</h6>
            <span class="text-base">Gift</span>
          </div>
        </div>

        <a class="button mt-[28px]" href="participates">Participate</a>
      </div>
    </div>

    <!-- Previous Challenges section -->
    <div class="pb-7">
      <div class="flex justify-between items-center pb-3">
        <h3 class="font-semibold text-2xl leading-7">Previous Challenges</h3>
        <%= link_to "See all", challenges_path(state: "finnished"), class: "text-2xl leading-none underline" %>
      </div>

      <!-- Slider -->
      <div data-controller="carousel" class="swiper-container relative pt-8"
        data-carousel-options-value='{"slidesPerView": "3"}'>
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <!-- Slides -->
          <div class="swiper-slide">
            <div class="flex flex-col bg-white">
              <%= image_tag("challenge1.png", alt: "img", class: "w-full max-w-full max-h-[320px] object-cover") %>

              <div class="flex gap-[1px]">
                <div class="py-2 px-6 bg-darkblue w-full">
                  <span class="text-white font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
                </div>

                <div class="py-2 px-6 bg-darkblue">
                  <span class="text-white font-bold leading-6">$400</span>
                </div>
              </div>

              <h3 class="px-6 my-6 text-2xl leading-7 font-bold line-clamp-2 h-14">Two Lines New Challenge Name That Is it</h3>

              <a class="flex justify-between items-center text-xl leading-[24px] py-3 px-6 border-t-[1px] border-darkblue" href="challenges">
                Results

                <svg width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
                </svg>
              </a>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="flex flex-col bg-white">
              <%= image_tag("pexels-rodion.png", alt: "img", class: "w-full max-w-full max-h-[320px] object-cover") %>

              <div class="flex gap-[1px]">
                <div class="py-2 px-6 bg-darkblue w-full">
                  <span class="text-white font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
                </div>

                <div class="py-2 px-6 bg-darkblue">
                  <span class="text-white font-bold leading-6">$400</span>
                </div>
              </div>

              <h3 class="px-6 my-6 text-2xl leading-7 font-bold line-clamp-2 h-14">Lorem ipsum dolor sit amet consectetur adipisic elit. Rem, ea. Modi illo nobis voluptatibus illum iste</h3>

              <a class="flex justify-between items-center text-xl leading-[24px] py-3 px-6 border-t-[1px] border-darkblue" href="challenges">
                Results

                <svg width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
                </svg>
              </a>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="flex flex-col bg-white">
              <%= image_tag("challenge1.png", alt: "img", class: "w-full max-w-full max-h-[320px] object-cover") %>

              <div class="flex gap-[1px]">
                <div class="py-2 px-6 bg-darkblue w-full">
                  <span class="text-white font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
                </div>

                <div class="py-2 px-6 bg-darkblue">
                  <span class="text-white font-bold leading-6">$400</span>
                </div>
              </div>

              <h3 class="px-6 my-6 text-2xl leading-7 font-bold line-clamp-2 h-14">One Lines Challenge</h3>

              <a class="flex justify-between items-center text-xl leading-[24px] py-3 px-6 border-t-[1px] border-darkblue" href="challenges">
                Results

                <svg width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
                </svg>
              </a>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="flex flex-col bg-white">
              <%= image_tag("challenge1.png", alt: "img", class: "w-full max-w-full max-h-[320px] object-cover") %>

              <div class="flex gap-[1px]">
                <div class="py-2 px-6 bg-darkblue w-full">
                  <span class="text-white font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
                </div>

                <div class="py-2 px-6 bg-darkblue">
                  <span class="text-white font-bold leading-6">$400</span>
                </div>
              </div>

              <h3 class="px-6 my-6 text-2xl leading-7 font-bold line-clamp-2 h-14">Two Lines New Challenge Name That Is it</h3>

              <a class="flex justify-between items-center text-xl leading-[24px] py-3 px-6 border-t-[1px] border-darkblue" href="challenges">
                Results

                <svg width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
                </svg>
              </a>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="flex flex-col bg-white">
              <%= image_tag("challenge1.png", alt: "img", class: "w-full max-w-full max-h-[320px] object-cover") %>

              <div class="flex gap-[1px]">
                <div class="py-2 px-6 bg-darkblue w-full">
                  <span class="text-white font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
                </div>

                <div class="py-2 px-6 bg-darkblue">
                  <span class="text-white font-bold leading-6">$400</span>
                </div>
              </div>

              <h3 class="px-6 my-6 text-2xl leading-7 font-bold line-clamp-2 h-14">Two Lines New Challenge Name That Is it</h3>

              <a class="flex justify-between items-center text-xl leading-[24px] py-3 px-6 border-t-[1px] border-darkblue" href="challenges">
                Results

                <svg width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
                </svg>
              </a>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="flex flex-col bg-white">
              <%= image_tag("challenge1.png", alt: "img", class: "w-full max-w-full max-h-[320px] object-cover") %>

              <div class="flex gap-[1px]">
                <div class="py-2 px-6 bg-darkblue w-full">
                  <span class="text-white font-medium leading-6">23 May 2021 - 25 Nov 2021</span>
                </div>

                <div class="py-2 px-6 bg-darkblue">
                  <span class="text-white font-bold leading-6">$400</span>
                </div>
              </div>

              <h3 class="px-6 my-6 text-2xl leading-7 font-bold line-clamp-2 h-14">Two Lines New Challenge Name That Is it</h3>

              <a class="flex justify-between items-center text-xl leading-[24px] py-3 px-6 border-t-[1px] border-darkblue" href="challenges">
                Results

                <svg width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
                </svg>
              </a>
            </div>
          </div>
        </div>

        <div class="swiper-pagination"></div>
      </div> 
    </div>

    <!-- Famous for section -->
    <div class="pt-[126px] pb-[136px] flex gap-[118px] relative overflow-hidden">
      <%= image_tag("cube1.svg", size: "810x814", alt: "img", class: "absolute top-[41px] right-0 z-[-1]") %>

      <h2 class="title max-w-[554px]">What are we famous for?</h2>

      <div class="flex flex-col items-start gap-16 mt-3">
        <p class="text-xl max-w-[528px]">Here we can place some different info about our company and challenges that we want to held. It’s all about good prints and 3D models, that you can imagine. Be a part of us today!</p>

        <div class="flex gap-11">
          <div class="flex flex-col gap-[3px]">
            <h6 class="font-bold text-2xl leading-none">245</h6>
            <span class="text-base">Total Participants</span>
          </div>

          <div class="flex flex-col gap-[3px]">
            <h6 class="font-bold text-2xl leading-none">$2300</h6>
            <span class="text-base">Reward Fond</span>
          </div>
        </div>

        <div class="flex flex-col items-start gap-[6px]">
          <div class="flex items-center gap-[10px]">
            <%= image_tag("our_jury1.jpg", size: "40x40", alt: "img", class: "rounded-full") %>
            <%= image_tag("our_jury2.jpg", size: "40x40", alt: "img", class: "rounded-full") %>
            <%= image_tag("our_jury3.jpg", size: "40x40", alt: "img", class: "rounded-full") %>
            <%= image_tag("our_jury4.jpg", size: "40x40", alt: "img", class: "rounded-full") %>
          </div>

          <p><%= link_to "Our Jury", juries_path %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/rulles.html.erb
<div class="container">
  <div class="flex justify-between items-start gap-5 pt-6 pb-10 border-b-[1px] border-darkblue">
    <h5 class="w-full max-w-[51%] text-2xl font-semibold">Rules</h5>
    <div class="w-full max-w-[49%] flex flex-col gap-[26px] text-xl">
      <p class="mb-2">All entries must be original and not previously published or submitted in any other competition.</p>
      <p class="mb-2">Entries must be submitted before the deadline stated on the website.</p>
      <p class="mb-2">Only one entry per person per week is allowed.</p>
      <p class="mb-2">Entries must adhere to the theme of the week.</p>
      <p class="mb-2">Participants must provide a brief description of their design and the 3D printing process used.</p>
      <p class="mb-2">Any inappropriate or offensive content will not be tolerated and will result in disqualification.</p>
      <p class="mb-2">Entries must not infringe on any third-party intellectual property rights.</p>
      <p class="mb-2">Entries must not contain any illegal, harmful, or offensive content.</p>
      <p class="mb-2">Entries must be 3D printable and must not require any special equipment or materials that are difficult to obtain.</p>
      <p class="mb-2">Entries must not have won any other 3D printing competition or award.</p>
      <p class="mb-2">Entries must be submitted in the correct file format and with all necessary files and documentation.</p>
      <p class="mb-2">Entries must not exceed a certain file size or print time limit.</p>
      <p class="mb-2">Participants must be 18 years or older or have parental consent to participate.</p>
      <p class="mb-2">Any attempt to cheat or manipulate the competition will result in disqualification.</p>
      <p class="mb-2">The judges' decision is final, and no correspondence will be entered into.</p>
      <p class="mb-2">The competition organizers reserve the right to modify or cancel the competition at any time.</p>
    </div>
  </div>
</div>

app/views/juries/index.html.erb
<div id="juries">
  <!-- Breadcrumb -->
  <div class="container">
    <a class="flex items-center gap-6 text-xl leading-[26px] my-6 w-fit" href="/">
      <svg class="rotate-180" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M1.31383 1.68617L8.7844 9.15674L1.31383 16.6273" stroke="#2A343E" stroke-width="2"/>
      </svg>

      Back To Home Page
    </a>
  </div>

  <!-- Hero section -->
  <div class="container">
    <div class="pb-[131px] flex gap-[118px] relative">
      <%= image_tag("cube3.svg", size: "810x457", alt: "img", class: "absolute bottom-0 right-0 z-[-1]") %>

      <h2 class="title leading-[1.2] w-full max-w-[554px]">Meet Our Jury</h2>

      <div class="flex flex-col items-start gap-9 mt-3">
        <p class="text-xl">
          In order to create unforgettible experience for our paticipants we invided the leaders of the masket.
          <br /><br />
          Here you can meet some outstanding figures of 3d printing industry.
        </p>

        <a class="button" href="challenges">All Challenges</a>
      </div>
    </div>
  </div>

  <!-- Juries -->
  <div class="bg-creamlight pb-24 pt-4">
    <div class="container">
      <% if @juries.any? %>
        <div class="grid grid-cols-2 gap-x-8">
          <% @juries.each do |jury| %>
            <%= link_to(jury_path(jury.id)) do %>
              <div class="flex items-center gap-8 py-6 border-b-[1px] border-darkblue">
                <%= image_tag(jury.avatar, size: "192x208", alt: "img", class: "w-full max-w-[192px] object-cover") %>
                <div class="flex flex-col items-start gap-8">
                  <div>
                    <h6 class="font-bold line-clamp-1"><%= jury.nick_name %></h6>
                    <p class="line-clamp-1"><%= "#{jury.first_name} #{jury.last_name}" %></p>
                  </div>

                  <p class="line-clamp-3 max-w-[256px]">A little description about the work I made. Fantastic story, that I tell.</p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="center">
          <div class="flex items-center gap-8 py-6 border-b-[1px] border-darkblue">
            <h2 class="title text-center">There are No available Juries at the moment</h2>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/juries/show.html.erb
<div class="container">
  <div class="flex items-center gap-36 pb-28">
  

    <div class="flex flex-col items-start gap-[14px]">
      <h1 class="font-bold text-2xl leading-[30px] max-w-sm pb-[22px]">
        <%= @jury.nick_name %>
        </br>
        <%= "#{@jury.first_name} #{@jury.last_name}" %>
      </h1>
      <p class="text-xl pb-[22px] max-w-md">Short description about this Jury. Check out these fantastic submissions to our Monday Prompts. Here will be some text, some more.</p>

      <div class="flex gap-20">
        <div class="flex flex-col gap-[3px]">
          <h6 class="font-bold text-2xl leading-none">24</h6>
          <span class="text-base">Finnished Challenges</span>
        </div>

        <a href="#" class="block p-3">
          <%= image_tag("instagram.svg", size: "20x20", alt: "fb") %>
        </a>
        <a href="#" class="block p-3">
          <%= image_tag("facebook.svg", size: "20x20", alt: "fb") %>
        </a>
        <a href="#" class="block p-3">
          <%= image_tag("facebook.svg", size: "20x20", alt: "fb") %>
        </a>
      </div>
    </div>

    <%= image_tag(@jury.avatar, size: "640x550", alt: "img", class: "w-full max-w-[49%]") %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-N5H3HJP');</script>
    <!-- End Google Tag Manager -->
    <script src="https://www.googleoptimize.com/optimize.js?id=OPT-PQ6BV28"></script>
    <title>PrintingWeeklyChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-SPYJ097H2E"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-SPYJ097H2E');
  </script>

  <!-- Google Analytics -->
  <script>
  window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
  ga('create', 'UA-177197692-1', 'auto');
  ga('send', 'pageview');
  </script>
  <script async src='https://www.google-analytics.com/analytics.js'></script>
  <!-- End Google Analytics -->

  <body class="font-sans bg-white text-darkblue flex flex-col min-h-screen overflow-x-hidden">
      <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N5H3HJP"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <%= render "shared/header" %>
    <main class="h-full w-full">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="w-full bg-darkblue mt-auto">
  <div class="container">
    <div class="flex items-center gap-32 py-8 text-white font-medium text-base leading-[21px]">
      <%= link_to root_path do %>
        <%= image_tag("logo_white.svg", size: "79x71") %>
      <% end %>

      <ul class="flex flex-col gap-2.5">
        <li>
          <%= link_to "Challenges", challenges_path%>
        </li>

        <li>
          <%= link_to "Rules", rulles_path %>
        </li>

        <li>
          <a href="juries">Jury</a>
        </li>
      </ul>

      <ul class="flex flex-col gap-2.5">
        <li>
          <a href="#">Facebook</a>
        </li>

        <li>
          <a href="#">Instagram</a>
        </li>

        <li>
          <a href="#">Twitter</a>
        </li>
      </ul>
    </div>
  </div>

  <hr class="w-full h-[2px] bg-darksecondary" />

  <div class="container">
  	<div class="text-gray text-xs py-4">
      <%= "© #{Time.zone.now.year}" %>
      <span>All rights reserved</span>
		</div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="w-full relative border-b-[1px] border-darkblue">
  <script src="https://www.googleoptimize.com/optimize.js?id=OPT-PQ6BV28"></script>
  <div class="container">
    <div class="flex justify-between items-center">
      <ul class="nav-list flex gap-16 text-base leading-[22px] font-semibold z-10">
        <li class="relative px-1 py-[29px]">
          <%= active_link_to "Challenges", challenges_path, active: :exact %>
        </li>

        <li class="relative px-1 py-[29px]">
          <%= active_link_to "Rules", rulles_path %>
        </li>

        <li class="relative px-1 py-[29px]">
          <%= active_link_to "Jury", juries_path %>
        </li>
      </ul>

      <a class="absolute mx-auto left-0 right-0 text-center z-0">
        <%= link_to root_path do %>
          <%= image_tag("logo.svg", size: "44x16", alt: "Printing Weekly", class: "mx-auto") %>
        <% end %>
      </a>

      <div class="flex items-center z-10">
        <a href="#" class="block p-3">
          <%= image_tag("facebook.svg", size: "20x20", alt: "fb") %>
        </a>

        <a href="#" class="block p-3">
          <%= image_tag("instagram.svg", size: "20x20", alt: "instagram") %>
        </a>

        <% unless current_user.present? %>
          <%= link_to 'Sign In', new_user_session_path, data: { trubo: false }, class: "button w-[216px] px-0 ml-3" %>
        <% else %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { trubo: false }, class: "button w-[216px] px-0 ml-3" %>
        <% end %>
      </div>
    </div>
  </div>
</header>